import * as fs from 'fs';
import * as path from 'path';
import { XanoColumn } from './lib/xano-client';
import { mapColumn, quoteIdent, PgColumn } from './lib/type-map';
import { renameTable, renameColumn, forceNullable, clearDefaults } from './lib/overrides';

interface SchemaTable {
  id: number;
  name: string;
  auth: boolean;
  columns: XanoColumn[];
}

const SCHEMA_FILE = path.resolve(__dirname, 'output', 'xano-schema.json');
const OUTPUT_FILE = path.resolve(__dirname, 'output', '0001_initial_schema.sql');

function topoSort(tables: SchemaTable[]): SchemaTable[] {
  const byId = new Map(tables.map(t => [t.id, t]));
  const deps = new Map<number, Set<number>>();

  for (const t of tables) {
    const d = new Set<number>();
    for (const c of t.columns) {
      const m = mapColumn(c);
      if (m.fkRefTableId !== undefined && m.fkRefTableId !== t.id && byId.has(m.fkRefTableId)) {
        d.add(m.fkRefTableId);
      }
    }
    deps.set(t.id, d);
  }

  const ordered: SchemaTable[] = [];
  const visited = new Set<number>();
  const visiting = new Set<number>();

  const visit = (id: number) => {
    if (visited.has(id)) return;
    if (visiting.has(id)) {
      console.warn(`  ! cycle detected involving table id ${id}; continuing`);
      return;
    }
    visiting.add(id);
    for (const dep of deps.get(id) ?? []) visit(dep);
    visiting.delete(id);
    visited.add(id);
    const t = byId.get(id);
    if (t) ordered.push(t);
  };

  for (const t of tables) visit(t.id);
  return ordered;
}

function renderColumn(pc: PgColumn): string | null {
  if (pc.skip) return `  -- ${quoteIdent(pc.name)} ${pc.pgType} -- SKIPPED: ${pc.note}`;
  const parts: string[] = [quoteIdent(pc.name), pc.pgType];
  if (!pc.nullable) parts.push('NOT NULL');
  if (pc.defaultSql) parts.push(`DEFAULT ${pc.defaultSql}`);
  return '  ' + parts.join(' ');
}

function applyOverrides(origTable: string, m: PgColumn): PgColumn {
  const renamed = { ...m, name: renameColumn(origTable, m.name) };
  if (forceNullable[origTable]?.includes(renamed.name)) {
    renamed.nullable = true;
  }
  if (clearDefaults[origTable]?.includes(renamed.name)) {
    renamed.defaultSql = undefined;
  }
  if (renamed.isList) {
    renamed.nullable = true;
  }
  return renamed;
}

function renderTable(t: SchemaTable, byId: Map<number, SchemaTable>): string {
  const origTable = t.name;
  const pgTable = renameTable(origTable);
  const lines: string[] = [];
  lines.push(`-- ---------------------------------------------------------------`);
  lines.push(`-- Table: ${pgTable}${origTable !== pgTable ? ` (renamed from ${origTable})` : ''}  (xano_id=${t.id}${t.auth ? ', auth' : ''})`);
  lines.push(`-- ---------------------------------------------------------------`);
  lines.push(`CREATE TABLE ${quoteIdent(pgTable)} (`);

  const mapped: PgColumn[] = t.columns.map(c => applyOverrides(origTable, mapColumn(c)));

  const body: string[] = [];

  for (const m of mapped) {
    if (m.skip) {
      body.push(`  -- ${quoteIdent(m.name)}: SKIPPED (${m.note})`);
      continue;
    }

    if (m.isPrimaryKey) {
      if (m.pgType === 'bigint') {
        body.push(`  ${quoteIdent(m.name)} bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY`);
      } else if (m.pgType === 'uuid') {
        body.push(`  ${quoteIdent(m.name)} uuid PRIMARY KEY DEFAULT gen_random_uuid()`);
      } else {
        body.push(`  ${quoteIdent(m.name)} ${m.pgType} PRIMARY KEY`);
      }
      continue;
    }

    const rendered = renderColumn(m);
    if (rendered) body.push(rendered);
    if (m.checkSql) body.push(`  ${m.checkSql}`);
  }

  for (const m of mapped) {
    if (m.fkRefTableId !== undefined && !m.isPrimaryKey) {
      const refOrig = byId.get(m.fkRefTableId);
      if (!refOrig) continue;
      const refPgTable = renameTable(refOrig.name);
      body.push(
        `  CONSTRAINT ${quoteIdent(`${pgTable}_${m.name}_fkey`)} FOREIGN KEY (${quoteIdent(m.name)}) ` +
        `REFERENCES ${quoteIdent(refPgTable)}(${quoteIdent('id')}) DEFERRABLE INITIALLY DEFERRED`
      );
    }
  }

  lines.push(body.join(',\n'));
  lines.push(');');
  lines.push('');

  lines.push(`ALTER TABLE ${quoteIdent(pgTable)} ENABLE ROW LEVEL SECURITY;`);
  lines.push(`-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task`);
  lines.push(`CREATE POLICY ${quoteIdent(`${pgTable}_all_migration_placeholder`)} ON ${quoteIdent(pgTable)} FOR ALL USING (true) WITH CHECK (true);`);
  lines.push('');

  for (const m of mapped) {
    if (m.fkRefTableId !== undefined && !m.isPrimaryKey) {
      lines.push(`CREATE INDEX ${quoteIdent(`${pgTable}_${m.name}_idx`)} ON ${quoteIdent(pgTable)} (${quoteIdent(m.name)});`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  if (!fs.existsSync(SCHEMA_FILE)) {
    console.error(`Schema file not found: ${SCHEMA_FILE}\nRun: npm run migrate:schema:export`);
    process.exit(1);
  }

  const tables: SchemaTable[] = JSON.parse(fs.readFileSync(SCHEMA_FILE, 'utf8'));
  const byId = new Map(tables.map(t => [t.id, t]));
  const ordered = topoSort(tables);

  console.log('> Topological order (parents → children):');
  ordered.forEach((t, i) => console.log(`  ${i + 1}. ${t.name} (id=${t.id})`));

  const out: string[] = [];
  out.push(`-- Generated by scripts/migration/02-generate-sql.ts`);
  out.push(`-- Source: Xano workspace metadata export`);
  out.push(`-- ${tables.length} tables, ${tables.reduce((n, t) => n + t.columns.length, 0)} columns`);
  out.push('');
  out.push('-- For a clean re-run during development only (strip before prod execution):');
  const dropOrder = [...ordered].reverse();
  for (const t of dropOrder) out.push(`DROP TABLE IF EXISTS ${quoteIdent(renameTable(t.name))} CASCADE;`);
  out.push('');
  out.push('BEGIN;');
  out.push('');

  for (const t of ordered) out.push(renderTable(t, byId));

  out.push('COMMIT;');
  out.push('');

  fs.writeFileSync(OUTPUT_FILE, out.join('\n'));
  console.log(`\n✓ Wrote ${OUTPUT_FILE}`);

  const notes: string[] = [];
  for (const t of tables) {
    for (const c of t.columns) {
      const m = mapColumn(c);
      if (m.note) notes.push(`  ${t.name}.${c.name}: ${m.note}`);
    }
  }
  if (notes.length) {
    console.log('\nNotes:');
    notes.forEach(n => console.log(n));
  }
}

main();
