-- Generated by scripts/migration/02-generate-sql.ts
-- Source: Xano workspace metadata export
-- 7 tables, 51 columns

-- For a clean re-run during development only (strip before prod execution):
DROP TABLE IF EXISTS "saved_offers" CASCADE;
DROP TABLE IF EXISTS "saved_location" CASCADE;
DROP TABLE IF EXISTS "reviews" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "post_codes" CASCADE;
DROP TABLE IF EXISTS "offers" CASCADE;
DROP TABLE IF EXISTS "location" CASCADE;

BEGIN;

-- ---------------------------------------------------------------
-- Table: location  (xano_id=2)
-- ---------------------------------------------------------------
CREATE TABLE "location" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "latitude" numeric NOT NULL,
  "longitude" numeric NOT NULL,
  "name" text NOT NULL,
  "end_date" date,
  "category" text NOT NULL,
  "url" text,
  "description" text NOT NULL,
  "tags" text[],
  "place_position" text NOT NULL,
  "type" text NOT NULL DEFAULT 'playground',
  CHECK ("type" IN ('playground', 'event')),
  "img_url" jsonb,
  "preview_img" jsonb[],
  "reviews" uuid[],
  "average_rating" numeric NOT NULL
);

ALTER TABLE "location" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "location_all_migration_placeholder" ON "location" FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------------
-- Table: offers  (xano_id=7)
-- ---------------------------------------------------------------
CREATE TABLE "offers" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "name" text NOT NULL,
  "description" text NOT NULL,
  "image" jsonb,
  "category" text NOT NULL,
  CHECK ("category" IN ('deals', 'benefits')),
  "preview_img" jsonb[],
  "url" text NOT NULL
);

ALTER TABLE "offers" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "offers_all_migration_placeholder" ON "offers" FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------------
-- Table: post_codes  (xano_id=6)
-- ---------------------------------------------------------------
CREATE TABLE "post_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "name" text NOT NULL,
  "code" text NOT NULL
);

ALTER TABLE "post_codes" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "post_codes_all_migration_placeholder" ON "post_codes" FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------------
-- Table: users (renamed from user_01)  (xano_id=1, auth)
-- ---------------------------------------------------------------
CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "email" text NOT NULL,
  -- "password": SKIPPED (password field deferred to auth task),
  "name" text NOT NULL,
  "code" text,
  "magic_link" jsonb,
  "is_admin" boolean NOT NULL
);

ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "users_all_migration_placeholder" ON "users" FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------------
-- Table: reviews  (xano_id=4)
-- ---------------------------------------------------------------
CREATE TABLE "reviews" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "rating" bigint NOT NULL,
  "review" text NOT NULL,
  "location_id" uuid,
  "user_id" uuid,
  "status" text NOT NULL DEFAULT 'pending',
  CHECK ("status" IN ('pending', 'approved', 'rejected')),
  CONSTRAINT "reviews_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "location"("id") DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "reviews_all_migration_placeholder" ON "reviews" FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX "reviews_location_id_idx" ON "reviews" ("location_id");
CREATE INDEX "reviews_user_id_idx" ON "reviews" ("user_id");

-- ---------------------------------------------------------------
-- Table: saved_location  (xano_id=3)
-- ---------------------------------------------------------------
CREATE TABLE "saved_location" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "user_id" uuid,
  "location_id" uuid,
  CONSTRAINT "saved_location_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT "saved_location_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "location"("id") DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE "saved_location" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "saved_location_all_migration_placeholder" ON "saved_location" FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX "saved_location_user_id_idx" ON "saved_location" ("user_id");
CREATE INDEX "saved_location_location_id_idx" ON "saved_location" ("location_id");

-- ---------------------------------------------------------------
-- Table: saved_offers  (xano_id=8)
-- ---------------------------------------------------------------
CREATE TABLE "saved_offers" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "user_id" uuid,
  "offers_id" bigint NOT NULL,
  CONSTRAINT "saved_offers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT "saved_offers_offers_id_fkey" FOREIGN KEY ("offers_id") REFERENCES "offers"("id") DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE "saved_offers" ENABLE ROW LEVEL SECURITY;
-- TODO: real RLS policy — placeholder below is wide-open for migration load; tighten in auth task
CREATE POLICY "saved_offers_all_migration_placeholder" ON "saved_offers" FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX "saved_offers_user_id_idx" ON "saved_offers" ("user_id");
CREATE INDEX "saved_offers_offers_id_idx" ON "saved_offers" ("offers_id");

COMMIT;
